name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
          spec: cypress/integration/cucumber-bdd-test/AnnuitiesDetails.feature

      - name: Generate report
        run: cd BHFCucumber && npm run cy:report
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: BHFCucumber/cypress/cucumber-report/
         
          