name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
          spec: cypress/integration/cucumber-bdd-test/AnnuitiesDetails.feature
          record: true
          env:
          CYPRESS_RECORD_KEY: d2006a51-864a-41d1-8327-08fc15430244
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
         
          